spring.application.name=ecommerce-app

# Active profile
spring.profiles.active=dev

# Jackson (date handling)
spring.jackson.time-zone=UTC
#spring.jackson.serialization.write-dates-as-timestamps=false

# Server
server.port=8090

# Logging
logging.level.root=INFO
